[tool.poetry]
name = "jupyter-logs-mining-extension"
version = "0.1.0"
description = ""
authors = ["konstantgr <konstantin.grotov@gmail.com>"]
readme = "README.md"
packages = [{include = "jupyter_logs_mining_extension"}]

[tool.poetry.dependencies]
python = "^3.11"
notebook = "6.1.5"
jupyter-contrib-nbextensions = "^0.7.0"
jupyter = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
